chore: add "security" commit type
influxdata/validate-semantic-github-messages pull request #18
Opened 2022-07-13 00:43 UTC by bnpfeife

2022-07-13 00:46 UTC, jacobmarble approved these changes

2022-07-13 00:47 UTC, jacobmarble requested changes
You'll need to regenerate the script, per the README. Also, please add a small unit test.

2022-07-13 00:52 UTC, bnpfeife commented
> You'll need to regenerate the script, per the README. Also, please add a small unit test.



> You'll need to regenerate the script, per the README. Also, please add a small unit test.

Sorry about that! I've added some tests and regenerated the config.

2022-07-28 14:36 UTC, bnpfeife commented
We've ended up using `feat(security)` and `fix(security)` instead, which should require no changes here.

2022-07-28 14:36 UTC, closed without merging